#!/bin/bash

filename="$1"

usage() {
    echo ''
    echo "Usage: `basename $0` <filename>"
    echo ' `filename` -- the .tex file to convert'
    echo ''
    exit 1;
}

if [ -z "$filename" ]; then
usage
fi

if [ "${filename##*.}" != 'tex' ]; then
usage
fi

file=$(basename "$filename")

pdflatex ${PWD}/$filename
unoconv -f doc ${PWD}/${filename%.*}.pdf